name: SkyWars
version: '${project.version}'
main: net.aerh.skywars.SkyWarsPlugin
api-version: '1.20'
load: STARTUP
authors: [Aerh]
commands:
  start:
    aliases:
      - sg
      - startgame
  games:
    aliases:
      - listgames
  gameinfo:
      aliases:
      - gi
  skipevent: